
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!


target 'Wow Patiant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'Alamofire', '~> 4.7'
 pod 'JBDatePicker'
 pod 'GoogleMaps'
 pod 'GooglePlaces'
 pod 'SDWebImage', '~> 4.0'
 # Pods for Wow Patiant

end
